version: '3'
services:
  api_bluebank_docker:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: api_bluebank_docker/api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=bluebank_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
     